# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payable',
            options={'verbose_name': '应付款项', 'verbose_name_plural': '应付款项'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '已付款项', 'verbose_name_plural': '已付款项'},
        ),
        migrations.AlterField(
            model_name='payable',
            name='no',
            field=models.CharField(max_length=100, verbose_name='应付款账单编号'),
        ),
        migrations.AlterField(
            model_name='payable',
            name='received_date',
            field=models.DateField(verbose_name='账单收到日期'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='已付款金额'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='付款汇率'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.Payable', verbose_name='应付款账单'),
        ),
    ]
