# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20170807_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transfer_charge',
        ),
    ]
