# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20170810_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payable',
            options={'verbose_name': '待付款项', 'verbose_name_plural': '待付款项'},
        ),
        migrations.AlterField(
            model_name='payable',
            name='no',
            field=models.CharField(max_length=100, verbose_name='待付款账单编号'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Currency', verbose_name='付款货币'),
        ),
    ]
