# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 14:30
from __future__ import unicode_literals

import base.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20170704_1509'),
        ('case', '0006_case_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField(default=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('no', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('applicant', models.CharField(blank=True, max_length=300, null=True)),
                ('app_date', models.DateField(blank=True, null=True)),
                ('case', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Client')),
            ],
            options={
                'abstract': False,
            },
            bases=(base.models.FakerMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
