# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_auto_20170712_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='case',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Case'),
        ),
    ]
