# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 15:03
from __future__ import unicode_literals

import base.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_auto_20170712_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField(default=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('no', models.CharField(max_length=100, null=True)),
                ('contractor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contractor_tel', models.CharField(blank=True, max_length=30, null=True)),
                ('contractor_mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('contractor_email', models.CharField(blank=True, max_length=200, null=True)),
                ('contractor_qq', models.CharField(blank=True, max_length=45, null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('case', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Case')),
            ],
            options={
                'abstract': False,
            },
            bases=(base.models.FakerMixin, models.Model),
        ),
    ]
