# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0011_auto_20170801_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='case',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='subcase',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
