# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_auto_20170810_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='settled',
        ),
        migrations.RemoveField(
            model_name='subcase',
            name='settled',
        ),
        migrations.AlterField(
            model_name='application',
            name='app_date',
            field=models.DateField(blank=True, null=True, verbose_name='申请日期'),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='application',
            name='case',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Case', verbose_name='关联案件'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='申请名称'),
        ),
        migrations.AlterField(
            model_name='application',
            name='no',
            field=models.CharField(max_length=100, verbose_name='申请编号'),
        ),
        migrations.AlterField(
            model_name='case',
            name='archive_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='档案号'),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Category', verbose_name='案件分类'),
        ),
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Client', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='case',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='结案'),
        ),
        migrations.AlterField(
            model_name='case',
            name='entry_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Country', verbose_name='进入国家'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=200, verbose_name='案件名称'),
        ),
        migrations.AlterField(
            model_name='case',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Owner', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='case',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Stage', verbose_name='所处阶段'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='case',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Case', verbose_name='关联合同'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractor_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='联系人Email'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractor_mobile',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='联系人手机'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractor_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人姓名'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractor_qq',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='联系人QQ'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractor_tel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='联系人电话'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='no',
            field=models.CharField(default='no-xxxx', max_length=100, verbose_name='合同编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_date',
            field=models.DateField(blank=True, null=True, verbose_name='签字日期'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
    ]
