# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0013_auto_20170810_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '案件分类', 'verbose_name_plural': '案件分类'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': '案件阶段', 'verbose_name_plural': '案件阶段'},
        ),
    ]
