# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_niceclassification_trademark_trademarknation_trademarknationnice'),
        ('case', '0015_auto_20170817_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='trademark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Trademark', verbose_name='商标'),
        ),
    ]
