# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20170818_2144'),
        ('case', '0016_case_trademark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='case',
        ),
        migrations.RemoveField(
            model_name='subcase',
            name='entry_country',
        ),
        migrations.AddField(
            model_name='subcase',
            name='trademarknation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.TrademarkNation', verbose_name='商标-进入国家'),
        ),
        migrations.AlterField(
            model_name='case',
            name='trademark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Trademark', verbose_name='商标'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
