# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0017_auto_20170818_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '案件', 'verbose_name_plural': '案件'},
        ),
        migrations.AlterModelOptions(
            name='subcase',
            options={'verbose_name': '分案', 'verbose_name_plural': '分案'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='case',
        ),
        migrations.AddField(
            model_name='contract',
            name='subcase',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.SubCase', verbose_name='关联合同'),
        ),
    ]
