# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_patternnation'),
        ('case', '0018_auto_20170818_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Pattern', verbose_name='专利'),
        ),
    ]
