# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0020_subcase_patternnation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcase',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_subcase', to='base.Client', verbose_name='代理'),
        ),
        migrations.AlterField(
            model_name='subcase',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Case', verbose_name='所属案件'),
        ),
        migrations.AlterField(
            model_name='subcase',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Stage', verbose_name='所处阶段'),
        ),
    ]
