# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 03:48
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_remove_payment_transfer_charge'),
        ('base', '0009_owner'),
        ('sale', '0007_auto_20170807_0959'),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField(default=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支出金额')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10, verbose_name='汇率')),
                ('incurred_date', models.DateField(blank=True, null=True, verbose_name='支出日期')),
                ('currency', models.ForeignKey(default='CNY', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Currency', verbose_name='货币')),
            ],
            options={
                'verbose_name_plural': '支出',
                'verbose_name': '支出',
            },
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'verbose_name': '支出类型', 'verbose_name_plural': '支出类型'},
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.ExpenseType', verbose_name='支出类型'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_charge', to='purchase.Payment', verbose_name='关联已付款项'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipts',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.Receipts', verbose_name='关联已收款项'),
        ),
    ]
