# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20170807_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipts',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_charge', to='sale.Receipts', verbose_name='关联已收款项'),
        ),
    ]
