# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0011_auto_20170801_1201'),
        ('expense', '0003_auto_20170807_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='subcase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.SubCase', verbose_name='关联分案件'),
        ),
    ]
