# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 04:39
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_expense_subcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=8, verbose_name='汇率'),
        ),
    ]
