# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_auto_20170809_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
