# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0009_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField(default=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预收款总额')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='预收款余额')),
                ('received_date', models.DateField(verbose_name='收到日期')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Client', verbose_name='客户')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Currency', verbose_name='货币')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
