# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 06:09
from __future__ import unicode_literals

import base.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField(default=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='收入类型')),
            ],
            options={
                'verbose_name': '收入类型',
                'verbose_name_plural': '收入类型',
            },
            bases=(base.models.FakerMixin, models.Model),
        ),
    ]
