# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 07:06
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_owner'),
        ('case', '0011_auto_20170801_1201'),
        ('income', '0002_incometype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField(default=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='收入金额')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=8, verbose_name='汇率')),
                ('incurred_date', models.DateField(blank=True, null=True, verbose_name='收入日期')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Currency', verbose_name='货币')),
                ('income_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='income.IncomeType', verbose_name='收入类型')),
                ('subcase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.SubCase', verbose_name='关联分案件')),
            ],
            options={
                'verbose_name': '其它收入',
                'verbose_name_plural': '其它收入',
            },
        ),
    ]
