# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_auto_20170809_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='income',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='incometype',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
