# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 02:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continents',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 7, 4, 2, 20, 21, 773919, tzinfo=utc))),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name_chs', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
