# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_continents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continents',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
