# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_continents_name_en'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Continents',
            new_name='Continent',
        ),
    ]
