# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20170704_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name_chs', models.CharField(blank=True, max_length=50, null=True)),
                ('name_en_short', models.CharField(max_length=50)),
                ('name_en_long', models.CharField(blank=True, max_length=100, null=True)),
                ('calling_code', models.CharField(max_length=50)),
                ('iso_code', models.CharField(max_length=5)),
                ('is_eu', models.BooleanField(default=False)),
                ('is_madrid', models.BooleanField(default=False)),
                ('is_oapi', models.BooleanField(default=False)),
                ('continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Continent')),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
    ]
