# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name_chs', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'currencies',
            },
        ),
    ]
