# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': '客户/代理', 'verbose_name_plural': '客户/代理'},
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Country', verbose_name='所在国家'),
        ),
        migrations.AlterField(
            model_name='client',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Currency', verbose_name='常用货币'),
        ),
        migrations.AlterField(
            model_name='client',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fax',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='传真'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='是否代理'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='移动电话'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='邮编'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='省/地区'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
