# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20170810_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'verbose_name': '洲', 'verbose_name_plural': '洲'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '国家', 'verbose_name_plural': '国家'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': '货币', 'verbose_name_plural': '货币'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': '所属部门', 'verbose_name_plural': '所属部门'},
        ),
    ]
