# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20170811_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='客户邮箱'),
        ),
    ]
