# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20170818_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trademarknationnice',
            old_name='trademark_nation',
            new_name='trademarknation',
        ),
    ]
