# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20170819_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField(default=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=200, verbose_name='专利名称')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Client', verbose_name='所属客户')),
            ],
            options={
                'verbose_name': '专利',
                'verbose_name_plural': '专利',
            },
        ),
    ]
