# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0011_auto_20170801_1201'),
        ('base', '0009_owner'),
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField(default=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='收款汇率')),
                ('received_date', models.DateField(verbose_name='收款日期')),
                ('transfer_charge', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Currency', verbose_name='收款货币')),
                ('deposit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='income.Deposit', verbose_name='客户预存款')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enabled', models.BooleanField(default=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('no', models.CharField(blank=True, max_length=100, null=True, verbose_name='收款账单编号')),
                ('sent_date', models.DateField(blank=True, null=True, verbose_name='发送日期')),
                ('sent', models.BooleanField(default=False, verbose_name='已发送')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='收款期限')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='收款金额')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Currency', verbose_name='货币')),
                ('subcase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.SubCase', verbose_name='关联分案')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='receipts',
            name='receivable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.Receivable', verbose_name='收款账单'),
        ),
    ]
