# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_receipts_unsettled_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipts',
            name='unsettled_amount',
        ),
        migrations.AddField(
            model_name='receivable',
            name='unsettled_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
