# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20170802_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivable',
            name='unsettled_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
