# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 13:41
from __future__ import unicode_literals

import decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20170802_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='已收款金额'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='transfer_charge',
            field=models.DecimalField(decimal_places=2, default=decimal.Decimal, max_digits=7, null=True, verbose_name='手续费'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='待收金额'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='待收期限'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='待收款账单编号'),
        ),
    ]
