# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20170802_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivable',
            name='sent',
        ),
        migrations.AddField(
            model_name='receivable',
            name='settled',
            field=models.BooleanField(default=False, verbose_name='客户是否付清'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='待收总金额'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='no',
            field=models.CharField(default='receivable-no-0002', max_length=100, verbose_name='待收款账单编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receivable',
            name='unsettled_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='未收总金额'),
        ),
    ]
