# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20170804_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=8, verbose_name='收款汇率'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receivable',
            name='sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='账单发送日期'),
        ),
    ]
