# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_remove_receipts_transfer_charge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipts',
            options={'verbose_name': '已收款项', 'verbose_name_plural': '已收款项'},
        ),
        migrations.AlterModelOptions(
            name='receivable',
            options={'verbose_name': '待收款项', 'verbose_name_plural': '待收款项'},
        ),
    ]
