# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_auto_20170810_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='receivable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.Receivable', verbose_name='待收款账单'),
        ),
    ]
